-- Liquibase changeset: Create users table
--liquibase formatted sql
--changeset author:unique-id1
CREATE TABLE users
(
    username VARCHAR(128) PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    enabled  boolean      NOT NULL
);

-- Liquibase changeset: Create groups table
--changeset author:unique-id2
CREATE TABLE groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(50) NOT NULL
);

-- Liquibase changeset: Create authorities table
--changeset author:unique-id3
CREATE TABLE authorities
(
    username  VARCHAR(128) NOT NULL,
    authority VARCHAR(128) NOT NULL,
    PRIMARY KEY (username, authority),
    CONSTRAINT fk_authorities_user FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

-- Liquibase changeset: Create group_authorities table
--changeset author:unique-id4
CREATE TABLE group_authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id  BIGINT      NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);

-- Liquibase changeset: Create group_members table
--changeset author:unique-id5
CREATE TABLE group_members
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(128),
    group_id  BIGINT NOT NULL,
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_name) REFERENCES users (username) ON DELETE CASCADE,
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);

-- Rollback statements
-- rollback DROP TABLE group_members;
-- rollback DROP TABLE group_authorities;
-- rollback DROP TABLE authorities;
-- rollback DROP TABLE groups;
-- rollback DROP TABLE users;