spring:
  application:
    name: you-dress-service-discovery

server:
  port: 8002

eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8002/eureka

  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"