spring:
  application:
    name: you-dress-service-gateway

server:
  port: 8003

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8002/eureka

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

  #spring:
  #  cloud:
  #    loadbalancer.ribbon.enabled: false
  #    gateway:
  #      routes:
  #        - id: organization-service
  #          uri: lb://organization-service
  #          predicates:
  #            - Path=/organization/**
  #          filters:
  #            - RewritePath=/organization/(?<path>.*), /$\{path}
  #        - id: licensing-service
  #          uri: lb://licensing-service
  #          predicates:
  #            - Path=/license/**
  #          filters:
  #            - RewritePath=/license/(?<path>.*), /$\{path}


  cloud:
    loadbalancer.ribbon.enabled: false
  gateway:
    routes:
      - id: you-dress-portal-backEnd
        uri: lb://you-dress-portal-backEnd
        predicates:
          - Path=/api/**, /oauth2/**, /logout
      - id: you-dress-authorization-server
        uri: lb://you-dress-authorization-server
        predicates:
          - Path=/auth-server/**
        filters:
          - StripPrefix=1
      - id: article-service
        uri: lb://article-service
        predicates:
          - Path=/article-service/**
        filters:
          - StripPrefix=1


management:
  endpoints:
    web:
      exposure:
        include: "*"


app:
  base-uri: http://127.0.0.1:4200

