spring:
  application:
    name: you-dress-portal-backEnd
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          angular-web-client:
            provider: spring
            client-id: angular-web-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8004"
            scope: openid, profile, articles.read, articles.write
        provider:
          spring:
            issuer-uri: "http://localhost:9000"
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8004

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8002/eureka

app:
  base-uri: http://127.0.0.1:4200